### ISSUE TITLE
Reference the new driver in the core-site.xml

### ISSUE THREAD

**Issue by millerbryan** [SparkTC/stocator#56]
The xml snippet shown references the class name for the new driver.  However, it doesn't include the filesystem path where the class is located.

```
<property>
    <name>fs.swift2d.impl</name>
    <value>com.ibm.stocator.fs.ObjectStoreFileSystem</value>
</property>
```

Where should the driver location be specified (using Ambari)?

Thanks

**Comment by gilv** [comment]
@millerbryan it just a reference to the class name, so that Hadoop eco-system (Spark, etc.. ) will know what class responsible for "swift2d". You can use core-sites.xml or provide configuration directly via hadoop configuration in the run time. 
You need to have stocator jar on the class path otherwise it will fail to load com.ibm.stocator.fs.ObjectStoreFileSystem.

**Comment by millerbryan** [comment]
@gilv - Thanks!  I will have a go a testing that out since I have to update my core-site.xml anyway.
